ScalableTeaching/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('courses/', include('courses.urls')),
    path('webhooks/', include('webhook.urls')),
    path('gitlab/', include('gitlab_surface_mock.urls')),
    path('', include('home.urls')),
    #path('endpoints/', include('request_endpoint.urls')),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('signup/', views.signup, name="signup"),
    path('logout/', LogoutView.as_view(next_page='index'), name='logout'),
    path('profile/', views.user_profile, name ="user_profile")

]

courses/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.


# Course Related Model
class Course(models.Model):
    name = models.CharField(max_length=200)
    students = models.ManyToManyField(User,  through="CourseUser")
    
    #class Meta:
    #    permissions = [
    #        ('create_task','Create Task'),
    #        ('create_')
    #    ]

    def __str__(self):
        return self.name




# Achievement Models - might spin these out later

class AchievementRarity(models.TextChoices):
    COMMON = 'CM', 'Common'
    RARE = 'RA', 'Rare'
    EPIC = 'EP', 'Epic'
    LEGENDARY = 'LG', 'Legendary'


class Achievement(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="achievements")
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    rarity = models.CharField(max_length=2, choices=AchievementRarity.choices, default=AchievementRarity.COMMON)
    point_value = models.IntegerField("Point Value",default=5)

    def is_earned_by(self, user):
        triggers = self.triggers.all()
        #print(triggers)
        return all( # Return all completed tests
            CourseUserTriggerProgress.objects.filter(user=user, trigger=trigger, fulfilled=True).exists() for trigger in triggers
        )
    
    def __str__(self):
        return self.name




class AchievementTrigger(models.Model):
    achievement = models.ForeignKey(Achievement, on_delete=models.CASCADE, related_name="triggers")
    triggering_test_name = models.CharField(max_length=200)
    triggering_status = models.BooleanField("Trigger on Test Success",default=True)

    def __str__(self):
        return self.achievement.name + " Trigger: " + self.triggering_test_name + " " + str(self.triggering_status)
    


# If I spin out the achievement models, spin out the
class CourseUser(models.Model):
    # This is a through model. It handles the relation.
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    gitlab_user_id = models.IntegerField(default=0)
    #started_tasks = models.OneToMany()
    achievements = models.ManyToManyField(Achievement, blank=True)
    points = models.IntegerField(default=0)
    leaderboard_optin = models.BooleanField(default=False)


class CourseUserTriggerProgress(models.Model):
    user = models.ForeignKey(CourseUser, on_delete=models.CASCADE, related_name="achievement_progress")
    trigger = models.ForeignKey(AchievementTrigger, on_delete=models.CASCADE)
    fulfilled = models.BooleanField(default=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user','trigger'],name="unique_user_trigger_progress")
        ]        

class TaskGroup(models.Model):
    name = models.CharField(max_length=200)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

class Task(models.Model): # This needs more
    name = models.CharField(max_length=200)
    task_group = models.ForeignKey(TaskGroup, on_delete=models.CASCADE, related_name='tasks')
    #base_repo_link = models.
    # Should have a base repo link to clone from but let's create the cloning functionality later. It is superfluous for a prototype
    

class StartedTask(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="started_tasks")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="started_tasks")
    started_at = models.DateTimeField(auto_now_add=True)

class QueuedAchievementToast(models.Model):
    received_at = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(CourseUser, on_delete=models.CASCADE)
    achievement = models.ForeignKey(Achievement, on_delete=models.CASCADE)


    # Wouldn't make sense to queue up the same achievement twice. 
    # Queue will be cleared, though. So will need to check if user has achievement before queueing
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user','achievement'], name="unique_user_achievement_toast")
        ]
    
    def __str__(self):
        return self.user.user.username + ": " + self.achievement.name



#class Subtask(models.Model):

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.update({
            'required': '',
            'name': 'username',
            'class': 'form-control',
            'id': 'username',
            'aria-describedby': 'usernameHelp'

        })
        self.fields["password1"].widget.attrs.update({
            'required': '',
            'type': 'password',
            'name': 'password1',
            'class': 'form-control',
            'id': 'password1',
            'aria-describedby': 'passwordHelp'

        })
        self.fields["password2"].widget.attrs.update({
            'required': '',
            'type': 'password',
            'name': 'password2',
            'class': 'form-control',
            'id': 'password2',
            'aria-describedby': 'password2Help'

        })

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

home/views.py
from django.shortcuts import render, redirect
from .forms import SignupForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from courses.models import CourseUser, Achievement

# Create your views here.

def index(request):
    return render(request, 'home.html')

def user_profile(request):
    best_accomplishment = CourseUser.objects.filter(user=request.user).order_by('-points').first() # Get course user objects and order by points in descending order, take the first element to get best accomplishment
    all_achievements = Achievement.objects.filter(courseuser__user=request.user).distinct()
    context = {"best_accomplishment": best_accomplishment, "all_achievements": all_achievements}

    return render(request, "user_profile.html", context)

def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password1")
            new_user = authenticate(username=username, password=password)
            if new_user is not None:
                login(request, new_user)
                messages.success(request, ("Registration Successful"))
                return redirect('courses')
        else:
            print(form.errors)
    else:
        form = SignupForm()

    context = {
        "form": form
    }
    return render(request, "signup.html", context)


def login_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('courses')
        else:
            messages.success(request, ("There was an error logging you in. Double check your credentials and try again."))
            return redirect('login')
    else:
        return render(request, 'login.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Base{% endblock %} | ScalableTeaching Reimplemenation</title>
        <!-- Load JQuery-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script> 
        <!-- Load Bootstrap -->
           <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
           
    </head>
    <body>

        {% include 'navbar.html'%}

        <!--Page Content goes here-->
        <div class="container">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>  
                    {% endfor %}
            {% endif %}

            {% block content %}
            {% endblock %}
        </div>

        <div id="div1">

        </div>


        <!-- Bootstrap JavaScript and optional dependency -->
         <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>


        <!--Global Toasts-->



        <div class="toast-container position-fixed bottom-0 end-0 p-3" style="z-index: 1080;" id="achievementToastContainer">
            <!-- Empty Because it's a container that will be added to through JavaScript -->
        </div>

   



        {% if request.user.is_authenticated %}
            <script>


                
                // Evaluate the rarity to its long name
                function evaluateRarity(rarityShorthand) {
                    const rarities = {"CM": "Common", "RA": "Rare", "EP": "Epic", "LG": "Legendary"}
                    return rarities[rarityShorthand];
                }

                // Toast Creation Helper Method
                function createAchievementToast(rarity, achievementName, achievementDescription, points) {
                    const toastId = 'toast' + Date.now() // Make sure each ID is unique
                    const toastHTML = `
                    <div id="${toastId}" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
                        <div class="toast-header">
                            <img src="" class="rounded me-2" alt="...">
                            <strong class="me-auto">Achievement Unlocked!</strong>
                            <small class="text-body-secondary">${rarity}</small>
                            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                        </div>
                        <div class="toast-body">
                            <strong>${achievementName}</strong>
                            <br />
                            ${achievementDescription}
                            <br />
                            <small class="text-body-secondary">${points} points</small>
                        </div>
                    </div>`

                    $('#achievementToastContainer').append(toastHTML);


                    const toastElement = $("#"+toastId);
                    const toast = new bootstrap.Toast(toastElement);
                    toast.show();

                    // Clean up after myself ffs
                    $(toastElement).on('hidden.bs.toast', function() {
                        $(this).remove();
                    });

                    

                }

                let pollInterval; 

                function pollAchievements() {
                    const pollUrl = "{% url 'poll_achievements' request.user.username %}";
                    
                    console.log("Polling for Achievements")
                    $.ajax({url: pollUrl, 
                        headers: {
                            "Achievement-Webhook-Token": "{{ ACHIEVEMENT_WEBHOOK_TOKEN }}"
                        },
                        success: function(result) {
                            resultObj = JSON.parse(result)
                            console.log(resultObj)
                            if (resultObj.length == 0) {
                                return;
                            } // Do nothing if no news
                                
                            //$("#div1").append(result + "<br>");
                            for (const toast of resultObj) {
                                let rarity = evaluateRarity(toast.rarity)
                                let name = toast.name
                                let desc =  toast.description
                                let points = toast.points
                                createAchievementToast(rarity, name, desc, points);
                            };
                            
                            
                            

                        },
                        error: function(xhr, status, error) {
                            if (xhr.status == 404) {
                                console.log("Endpoint returned 404, it is either down or there is no user. Stopping polling")
                                clearInterval(pollInterval);
                            }
                        }
                    });
                    
                }

                pollAchievements();

                pollInterval = setInterval(pollAchievements, 1000);
            </script>
        {% endif %}
    </body>
</html>

templates/course_page.html
{% extends "base.html" %}
{% block title %}{{ course.name }}{% endblock %}

{% block content %}
<br>
<br>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'courses' %}">Courses</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{course.name}}</li>
  </ol>
</nav>


<div class="h-100 p-5 bg-body-tertiary border rounded-3">

    <div class="container">
        <div class="row align-items-start">
            <div class="col-md-9">
                <h1>{{ course.name }}</h1>
                <h5>{{ course_user.points }} points</h5>
            </div>
            <hr>
            <p>The following tasks and subtasks are front-end only, intended to show what tasks and subtasks would have looked like if I were to properly implement them.</p>
            <div class="list-group">
                <a href="#" class="list-group-item list-group-item-action list-group-item-dark" aria-current="true">
                    <div class="text-center">
                        <h5 class="mb-1" align="center">Lesson 1</h5>
                    </div>
                </a>
                <a href="#" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">Design Patterns</h5>
                        <small class="text-body-secondary">Opened 3 days ago</small>
                    </div>
                    <p class="mb-1">Closes 1 month from now.</p>
                </a>
            </div>
            <div class="list-group mt-4">
                <a href="#" class="list-group-item list-group-item-action list-group-item-dark" aria-current="true">
                    <div class="text-center">
                        <h5 class="mb-1" align="center">Lesson 2</h5>
                    </div>
                </a>
                <a href="#" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">Ciphers &amp; Polymorphism</h5>
                        <small class="text-body-secondary">Opened 3 days ago</small>
                    </div>
                    <p class="mb-1">Closes 1 month from now.</p>
                </a>
                <a href="#" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">Avalonia Introduction</h5>
                        <small class="text-body-secondary">Opened 3 days ago</small>
                    </div>
                    <p class="mb-1">Closes 1 month from now.</p>
                </a>
            </div>
        </div>
    </div>

</div>


{% endblock %}

templates/courses_list.html
{% extends "base.html" %}
{% block title %}Courses{% endblock %}

{% block content %}
<br>
<br>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Courses</a></li>
  </ol>
</nav>

<h1>Courses</h1>

<br>

<div class="h-100 p-5 bg-body-tertiary border rounded-3">
    

    <div class="row row-cols-4">
        {% for course_user in course_users %}
        
        <div class="col">
            <div class="card" style="width: 18rem;">
                <img src="" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{course_user.course.name}}</h5>
                    <h6 class="card-subtitle mb-2 text-body-secondary"></h6>
                    <p class="card-text"></p>
                    <p class="card-text"><small class="text-body-secondary">{{ course_user.points }} points</small></p>
                  <a href="{% url 'course' course_user.course.id %}" class="btn btn-primary">Go to course</a>
                </div>
              </div>
        </div>
        {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %}


<!-- Jumbotron Borrowed from https://getbootstrap.com/docs/5.3/examples/jumbotrons/ -->
<div class="container my-5">
     <div class="p-5 text-center bg-body-tertiary rounded-3">
        <h1 class="text-body-emphasis">Assignment Tracking</h1> 
        <p class="col-lg-8 mx-auto fs-5 text-muted">
            This page keeps track of your assignments and tells you instantly when an assignment has been passed.
        </p>
        <div class="d-inline-flex gap-2 mb-5"> 
            <button class="d-inline-flex align-items-center btn btn-success btn-lg px-4 rounded-pill" type="button">
                Get Started Now
            </button>
        </div> 
    </div> 
</div>

<div class="container px-4 py-5" id="featured-3">
    <h2 class="pb-2 border-bottom">Statistics</h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
        <div class="feature col">
            <div class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3">
            </div>
            <h3 class="fs-2 text-body-emphasis">Assignments and Projects</h3>
            <p>In total, <strong>191</strong> assignments have been created with an associated <strong>3704</strong> projects.</p> 
        </div> 
        <div class="feature col"> 
            <div class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3"> 
            </div> 
            <h3 class="fs-2 text-body-emphasis">0 Builds</h3>
            <p>During the last month <strong>0</strong> builds have run, with an averge run time of <strong>0.00</strong> seconds</p>
        </div> 
        <div class="feature col">
            <div class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3"> 
            </div>
            <h3 class="fs-2 text-body-emphasis">Average Queue Time</h3> 
            <p>Over the last month the average queue time has been <strong>0.00</strong> seconds</p> 
        </div>
    </div>
</div>



{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}Log in{% endblock %}

{% block content %}

{% if form.errors %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>There was an error with your form.</strong> Check below for details
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>  
{% endif %}


<div class="h-100 p-5 bg-body-tertiary border rounded-3">
    <div class="container">
        <form method="POST" action="{% url 'login' %}">
            {% csrf_token %}
            <div class="mb-3">
                <label for="username" class="form-label">Username</label>
                <div id="usernameHelp" class="form-text">This is the one you picked at sign up.</div>
                <input type="text" class="form-control" name="username" id="username" aria-describedby="">
            </div>

            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <div id="passwordHelp" class="form-text">Never give out your password to strangers!</div>
                <input type="password" class="form-control" name="password" id="password">
            </div>

            <button type="Submit" class="btn btn-success">Log in</button>
        </form>
    </div>
</div>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary"  data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">ScalableTeaching</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'courses' %}">Courses</a>
            </li>
            <li class="nav-item navbar-text active"><a href="{% url 'user_profile' %}" class="bg-success active" style="border-radius: .25em; padding: .25em; color:#FFFFFF;">{{request.user}}</a></li>
            <li class="nav-item active">
                <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-link nav-link active">Logout</button>
                </form>
            </li>
        {% else %}
            <li class="nav-item"><a href="/login" class="btn btn-success">Login</a></li>
        {% endif %}
      </ul>

    </div>
  </div>
</nav>

templates/signup.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}

{% block content %}

{% if form.errors %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>There was an error with your form.</strong> Check below for details
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>  
{% endif %}


<div class="h-100 p-5 bg-body-tertiary border rounded-3">
    <div class="container">
        <form method="POST" action="{% url 'signup' %}">
            {% csrf_token %}
            <div class="mb-3">
                <label for="username" class="form-label">Username</label>
                <div id="usernameHelp" class="form-text">Pick a unique username.</div>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label for="password1" class="form-label">Password</label>
                <div id="passwordHelp" class="form-text">Pick a strong and secure password.</div>
                {{ form.password1 }}
            </div>

            <div class="mb-3">
                <label for="password2" class="form-label">Repeat Password</label>
                <div id="password2Help" class="form-text">Now type it again.</div>
                {{ form.password2 }}
            </div>

            <button type="Submit" class="btn btn-success">Sign up</button>
        </form>
    </div>
</div>
{% endblock %}

templates/user_profile.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}

{% block content %}
<br> <br>


<div class="h-100 p-5 bg-body-tertiary border rounded-3">
    <div class="container">
        <h1>{{request.user.username}}</h1>
        <h5>Best Accomplishment: {{ best_accomplishment.course.name }} - {{ best_accomplishment.points }} points</h5>
        <hr>
        <br>
        <h2>Achievements</h2>
        <div class="row row-cols-4">
            {% for achievement in all_achievements %}
            <div class="col">
                <div class="card" style="width: 18rem;">
                    <img src="" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">{{achievement.name }}</h5>
                        <h6 class="card-subtitle mb-2 text-body-secondary"></h6>
                        <p class="card-text" id="rarity-{{achievement.name}}">{{ achievement.get_rarity_display}}</p>
                        <p class="card-text"><small class="text-body-secondary">{{ achievement.point_value }} points</small></p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<script>


</script>
{% endblock %}